predict_with_cloud_node:
  ros__parameters:
    use_sim_time: True
    camera_info_topic: "/zed2i/depth_camera/camera_info"
    lidar_topic: "/zed2i/depth_camera/points"
    yolo_result_topic: "yolo_result"
    yolo_3d_result_topic: "yolo_3d_result"
    cluster_tolerance: 0.1
    voxel_leaf_size: 0.07
    min_cluster_size: 10
    max_cluster_size: 700
    ransac_distance_threshold: 0.03
    gz_camera_convention: true